In [1]:
!pip install keras keras_nlp tensorflow tensorflow-text

In [63]:
import keras, keras_nlp

In [120]:
string_arr_text = ["Bengaluru is the garden city of India", "Bengaluru is the tech hub"]

In [121]:
preprocessor = keras_nlp.models.AlbertPreprocessor.from_preset("albert_base_en_uncased")

In [122]:
preprocessor(string_arr_text)

{'token_ids': <tf.Tensor: shape=(2, 512), dtype=int32, numpy=
 array([[ 2, 13,  1, ...,  0,  0,  0],
        [ 2, 13,  1, ...,  0,  0,  0]], dtype=int32)>,
 'segment_ids': <tf.Tensor: shape=(2, 512), dtype=int32, numpy=
 array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=int32)>,
 'padding_mask': <tf.Tensor: shape=(2, 512), dtype=bool, numpy=
 array([[ True,  True,  True, ..., False, False, False],
        [ True,  True,  True, ..., False, False, False]])>}

In [123]:
preprocessor = keras_nlp.models.AlbertPreprocessor.from_preset("albert_large_en_uncased")

In [124]:
preprocessor(string_arr_text)

{'token_ids': <tf.Tensor: shape=(2, 512), dtype=int32, numpy=
 array([[ 2, 13,  1, ...,  0,  0,  0],
        [ 2, 13,  1, ...,  0,  0,  0]], dtype=int32)>,
 'segment_ids': <tf.Tensor: shape=(2, 512), dtype=int32, numpy=
 array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=int32)>,
 'padding_mask': <tf.Tensor: shape=(2, 512), dtype=bool, numpy=
 array([[ True,  True,  True, ..., False, False, False],
        [ True,  True,  True, ..., False, False, False]])>}

In [125]:
preprocessor = keras_nlp.models.AlbertPreprocessor.from_preset("albert_extra_extra_large_en_uncased")

In [126]:
preprocessor(string_arr_text)

{'token_ids': <tf.Tensor: shape=(2, 512), dtype=int32, numpy=
 array([[ 2, 13,  1, ...,  0,  0,  0],
        [ 2, 13,  1, ...,  0,  0,  0]], dtype=int32)>,
 'segment_ids': <tf.Tensor: shape=(2, 512), dtype=int32, numpy=
 array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=int32)>,
 'padding_mask': <tf.Tensor: shape=(2, 512), dtype=bool, numpy=
 array([[ True,  True,  True, ..., False, False, False],
        [ True,  True,  True, ..., False, False, False]])>}

In [127]:
preprocessor = keras_nlp.models.AlbertPreprocessor.from_preset("albert_extra_large_en_uncased")

In [128]:
preprocessor(string_arr_text)

{'token_ids': <tf.Tensor: shape=(2, 512), dtype=int32, numpy=
 array([[ 2, 13,  1, ...,  0,  0,  0],
        [ 2, 13,  1, ...,  0,  0,  0]], dtype=int32)>,
 'segment_ids': <tf.Tensor: shape=(2, 512), dtype=int32, numpy=
 array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=int32)>,
 'padding_mask': <tf.Tensor: shape=(2, 512), dtype=bool, numpy=
 array([[ True,  True,  True, ..., False, False, False],
        [ True,  True,  True, ..., False, False, False]])>}

In [133]:
preprocessor = keras_nlp.models.BertPreprocessor.from_preset("bert_tiny_en_uncased")

In [134]:
preprocessor(string_arr_text)

{'token_ids': <tf.Tensor: shape=(2, 512), dtype=int32, numpy=
 array([[  101,  8191, 14129, ...,     0,     0,     0],
        [  101,  8191, 14129, ...,     0,     0,     0]], dtype=int32)>,
 'segment_ids': <tf.Tensor: shape=(2, 512), dtype=int32, numpy=
 array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=int32)>,
 'padding_mask': <tf.Tensor: shape=(2, 512), dtype=bool, numpy=
 array([[ True,  True,  True, ..., False, False, False],
        [ True,  True,  True, ..., False, False, False]])>}

In [135]:
preprocessor = keras_nlp.models.BertPreprocessor.from_preset("bert_small_en_uncased")

In [136]:
preprocessor(string_arr_text)

{'token_ids': <tf.Tensor: shape=(2, 512), dtype=int32, numpy=
 array([[  101,  8191, 14129, ...,     0,     0,     0],
        [  101,  8191, 14129, ...,     0,     0,     0]], dtype=int32)>,
 'segment_ids': <tf.Tensor: shape=(2, 512), dtype=int32, numpy=
 array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=int32)>,
 'padding_mask': <tf.Tensor: shape=(2, 512), dtype=bool, numpy=
 array([[ True,  True,  True, ..., False, False, False],
        [ True,  True,  True, ..., False, False, False]])>}

In [137]:
preprocessor = keras_nlp.models.BertPreprocessor.from_preset("bert_base_en_uncased")

In [138]:
preprocessor(string_arr_text)

{'token_ids': <tf.Tensor: shape=(2, 512), dtype=int32, numpy=
 array([[  101,  8191, 14129, ...,     0,     0,     0],
        [  101,  8191, 14129, ...,     0,     0,     0]], dtype=int32)>,
 'segment_ids': <tf.Tensor: shape=(2, 512), dtype=int32, numpy=
 array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=int32)>,
 'padding_mask': <tf.Tensor: shape=(2, 512), dtype=bool, numpy=
 array([[ True,  True,  True, ..., False, False, False],
        [ True,  True,  True, ..., False, False, False]])>}

In [139]:
preprocessor = keras_nlp.models.BloomPreprocessor.from_preset("bloom_560m_multi")

In [140]:
preprocessor(string_arr_text)

{'token_ids': <tf.Tensor: shape=(2, 2048), dtype=int32, numpy=
 array([[     1, 209443,   5046, ...,      3,      3,      3],
        [     1, 209443,   5046, ...,      3,      3,      3]], dtype=int32)>,
 'padding_mask': <tf.Tensor: shape=(2, 2048), dtype=bool, numpy=
 array([[ True,  True,  True, ..., False, False, False],
        [ True,  True,  True, ..., False, False, False]])>}

In [141]:
preprocessor = keras_nlp.models.BloomPreprocessor.from_preset("bloom_3b_multi")

100%|██████████| 453/453 [00:00<00:00, 474kB/s]
100%|██████████| 11.9M/11.9M [00:00<00:00, 19.2MB/s]
100%|██████████| 3.98M/3.98M [00:00<00:00, 9.23MB/s]


In [142]:
preprocessor(string_arr_text)

{'token_ids': <tf.Tensor: shape=(2, 2048), dtype=int32, numpy=
 array([[     1, 209443,   5046, ...,      3,      3,      3],
        [     1, 209443,   5046, ...,      3,      3,      3]], dtype=int32)>,
 'padding_mask': <tf.Tensor: shape=(2, 2048), dtype=bool, numpy=
 array([[ True,  True,  True, ..., False, False, False],
        [ True,  True,  True, ..., False, False, False]])>}

In [143]:
preprocessor = keras_nlp.models.DebertaV3Preprocessor.from_preset("deberta_v3_extra_small_en")

In [144]:
preprocessor(string_arr_text)

{'token_ids': <tf.Tensor: shape=(2, 512), dtype=int32, numpy=
 array([[    1, 27263,   269, ...,     0,     0,     0],
        [    1, 27263,   269, ...,     0,     0,     0]], dtype=int32)>,
 'padding_mask': <tf.Tensor: shape=(2, 512), dtype=bool, numpy=
 array([[ True,  True,  True, ..., False, False, False],
        [ True,  True,  True, ..., False, False, False]])>}

In [145]:
preprocessor = keras_nlp.models.DebertaV3Preprocessor.from_preset("deberta_v3_small_en")

100%|██████████| 424/424 [00:00<00:00, 531kB/s]
100%|██████████| 2.35M/2.35M [00:00<00:00, 6.06MB/s]


In [146]:
preprocessor(string_arr_text)

{'token_ids': <tf.Tensor: shape=(2, 512), dtype=int32, numpy=
 array([[    1, 27263,   269, ...,     0,     0,     0],
        [    1, 27263,   269, ...,     0,     0,     0]], dtype=int32)>,
 'padding_mask': <tf.Tensor: shape=(2, 512), dtype=bool, numpy=
 array([[ True,  True,  True, ..., False, False, False],
        [ True,  True,  True, ..., False, False, False]])>}

In [147]:
preprocessor = keras_nlp.models.DistilBertPreprocessor.from_preset("distil_bert_base_en")

100%|██████████| 581/581 [00:00<00:00, 907kB/s]
100%|██████████| 208k/208k [00:00<00:00, 1.17MB/s]


In [148]:
preprocessor(string_arr_text)

{'token_ids': <tf.Tensor: shape=(2, 512), dtype=int32, numpy=
 array([[  101,  7756, 12328, ...,     0,     0,     0],
        [  101,  7756, 12328, ...,     0,     0,     0]], dtype=int32)>,
 'padding_mask': <tf.Tensor: shape=(2, 512), dtype=bool, numpy=
 array([[ True,  True,  True, ..., False, False, False],
        [ True,  True,  True, ..., False, False, False]])>}

In [149]:
preprocessor = keras_nlp.models.ElectraPreprocessor.from_preset("electra_small_discriminator_uncased_en")

100%|██████████| 559/559 [00:00<00:00, 841kB/s]
100%|██████████| 226k/226k [00:00<00:00, 1.20MB/s]


In [150]:
preprocessor(string_arr_text)

{'token_ids': <tf.Tensor: shape=(2, 512), dtype=int32, numpy=
 array([[  101,  8191, 14129, ...,     0,     0,     0],
        [  101,  8191, 14129, ...,     0,     0,     0]], dtype=int32)>,
 'segment_ids': <tf.Tensor: shape=(2, 512), dtype=int32, numpy=
 array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=int32)>,
 'padding_mask': <tf.Tensor: shape=(2, 512), dtype=bool, numpy=
 array([[ True,  True,  True, ..., False, False, False],
        [ True,  True,  True, ..., False, False, False]])>}

In [151]:
preprocessor = keras_nlp.models.ElectraPreprocessor.from_preset("electra_small_generator_uncased_en")

In [152]:
preprocessor(string_arr_text)

{'token_ids': <tf.Tensor: shape=(2, 512), dtype=int32, numpy=
 array([[  101,  8191, 14129, ...,     0,     0,     0],
        [  101,  8191, 14129, ...,     0,     0,     0]], dtype=int32)>,
 'segment_ids': <tf.Tensor: shape=(2, 512), dtype=int32, numpy=
 array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=int32)>,
 'padding_mask': <tf.Tensor: shape=(2, 512), dtype=bool, numpy=
 array([[ True,  True,  True, ..., False, False, False],
        [ True,  True,  True, ..., False, False, False]])>}

In [153]:
preprocessor = keras_nlp.models.ElectraPreprocessor.from_preset("electra_large_generator_uncased_en")

In [154]:
preprocessor(string_arr_text)

{'token_ids': <tf.Tensor: shape=(2, 512), dtype=int32, numpy=
 array([[  101,  8191, 14129, ...,     0,     0,     0],
        [  101,  8191, 14129, ...,     0,     0,     0]], dtype=int32)>,
 'segment_ids': <tf.Tensor: shape=(2, 512), dtype=int32, numpy=
 array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=int32)>,
 'padding_mask': <tf.Tensor: shape=(2, 512), dtype=bool, numpy=
 array([[ True,  True,  True, ..., False, False, False],
        [ True,  True,  True, ..., False, False, False]])>}

In [155]:
preprocessor = keras_nlp.models.FNetPreprocessor.from_preset("f_net_base_en")

In [156]:
preprocessor(string_arr_text)

{'token_ids': <tf.Tensor: shape=(2, 512), dtype=int32, numpy=
 array([[    4, 16135,    34, ...,     3,     3,     3],
        [    4, 16135,    34, ...,     3,     3,     3]], dtype=int32)>,
 'segment_ids': <tf.Tensor: shape=(2, 512), dtype=int32, numpy=
 array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=int32)>}