In [1]:
!pip install keras keras_nlp tensorflow tensorflow-text

In [63]:
import keras, keras_nlp

In [120]:
string_arr_text = ["Bengaluru is the garden city of India", "Bengaluru is the tech hub"]

In [171]:
preprocessor = keras_nlp.models.AlbertPreprocessor.from_preset("albert_base_en_uncased")

In [172]:
preprocessor(string_arr_text)

{'token_ids': <tf.Tensor: shape=(2, 512), dtype=int32, numpy=
 array([[ 2, 13,  1, ...,  0,  0,  0],
        [ 2, 13,  1, ...,  0,  0,  0]], dtype=int32)>,
 'segment_ids': <tf.Tensor: shape=(2, 512), dtype=int32, numpy=
 array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=int32)>,
 'padding_mask': <tf.Tensor: shape=(2, 512), dtype=bool, numpy=
 array([[ True,  True,  True, ..., False, False, False],
        [ True,  True,  True, ..., False, False, False]])>}

In [173]:
model = keras_nlp.models.AlbertBackbone.from_preset("albert_base_en_uncased")

100%|██████████| 611/611 [00:00<00:00, 839kB/s]
100%|██████████| 44.6M/44.6M [00:01<00:00, 26.1MB/s]


In [174]:
model(preprocessor(string_arr_text))

{'sequence_output': <tf.Tensor: shape=(2, 512, 768), dtype=float32, numpy=
 array([[[ 0.29109532,  0.59039575,  0.57341796, ..., -1.7762976 ,
           0.8334062 ,  0.22888707],
         [ 0.23810953,  0.03257053,  0.14244957, ...,  0.13890208,
           0.97672796,  0.33284622],
         [-2.0244946 , -1.1321733 ,  1.7023356 , ...,  0.7105138 ,
           0.21753633, -1.2893486 ],
         ...,
         [-1.6347158 , -0.47780624,  0.7117915 , ...,  0.30713838,
           1.982284  , -1.0579503 ],
         [-1.5658598 , -0.40983802,  0.42121565, ..., -0.32397833,
           1.7305362 , -1.3411301 ],
         [ 0.10584101,  0.09978956, -0.0369747 , ..., -0.15564626,
           0.11278631,  0.18881346]],
 
        [[ 0.61990905,  1.5432444 ,  0.2692907 , ..., -1.582385  ,
           1.1010177 , -0.330584  ],
         [ 0.5509646 , -0.52529824, -0.445274  , ...,  0.2537047 ,
           1.1254579 , -0.5993581 ],
         [-0.95211315, -1.5976503 ,  1.5780841 , ...,  1.4106764 ,
         

In [175]:
preprocessor = keras_nlp.models.AlbertPreprocessor.from_preset("albert_large_en_uncased")

In [176]:
model = keras_nlp.models.AlbertBackbone.from_preset("albert_large_en_uncased")

100%|██████████| 610/610 [00:00<00:00, 699kB/s]
100%|██████████| 67.5M/67.5M [00:02<00:00, 31.8MB/s]


In [177]:
model(preprocessor(string_arr_text))

{'sequence_output': <tf.Tensor: shape=(2, 512, 1024), dtype=float32, numpy=
 array([[[ 0.2770636 , -0.1698493 ,  0.08749533, ..., -0.05548593,
           0.01278315,  0.6963581 ],
         [-0.72688234, -0.7326043 , -0.38781083, ...,  0.43813923,
          -1.4152989 , -0.06530092],
         [ 0.27033916,  0.19000015, -1.3199514 , ...,  0.1392531 ,
          -0.8895735 , -1.2217932 ],
         ...,
         [ 0.2773431 ,  0.66927105, -0.04740419, ..., -0.0374825 ,
          -0.77075374,  0.8259914 ],
         [ 0.518646  ,  0.66057897, -0.32028687, ...,  0.31278884,
          -0.5839745 ,  0.7095484 ],
         [ 0.41107494,  0.6453438 , -0.05412903, ...,  0.1492914 ,
          -0.58254355,  0.84967136]],
 
        [[-0.14092839, -0.33164838, -0.12895659, ..., -0.5563805 ,
          -0.5602438 ,  0.4876629 ],
         [-0.50146997,  0.06613347, -0.43767482, ...,  0.23815918,
          -1.0131388 , -0.3858407 ],
         [ 0.13780132, -0.06435348, -0.63802165, ..., -0.45307332,
        

In [179]:
preprocessor = keras_nlp.models.BertPreprocessor.from_preset("bert_tiny_en_uncased")

In [180]:
model = keras_nlp.models.BertBackbone.from_preset("bert_tiny_en_uncased")

100%|██████████| 507/507 [00:00<00:00, 754kB/s]
100%|██████████| 16.8M/16.8M [00:00<00:00, 19.2MB/s]


In [181]:
model(preprocessor(string_arr_text))

{'sequence_output': <tf.Tensor: shape=(2, 512, 128), dtype=float32, numpy=
 array([[[-0.00770359,  0.22362009, -3.8013916 , ..., -0.7977207 ,
          -1.6880293 ,  1.7669994 ],
         [-1.6496015 ,  0.15249002, -1.1784112 , ..., -1.7867173 ,
          -1.1260904 ,  0.7795008 ],
         [-1.5600612 , -0.21953619, -1.0176723 , ..., -1.7762308 ,
          -0.33892816,  2.633414  ],
         ...,
         [-0.30527773,  0.28472295, -0.75336015, ..., -1.456626  ,
          -0.9782943 ,  1.2421558 ],
         [-0.49452662,  0.41166344, -0.9690726 , ..., -1.2961192 ,
          -1.5198567 ,  0.53979856],
         [ 0.0641519 , -0.19211993, -2.706879  , ..., -0.68697417,
          -1.4666362 ,  1.7109971 ]],
 
        [[-0.354321  ,  0.9647313 , -3.847001  , ..., -0.80586714,
          -0.9092316 ,  1.3984995 ],
         [-1.835139  ,  0.6671057 , -1.078124  , ..., -1.630855  ,
          -0.78849745,  0.456828  ],
         [-1.4289438 ,  0.30635625, -0.9468864 , ..., -1.7343024 ,
         