In [1]:
!pip install keras keras_nlp tensorflow tensorflow-text

In [63]:
import keras, keras_nlp

In [120]:
string_arr_text = ["Bengaluru is the garden city of India", "Bengaluru is the tech hub"]

In [171]:
preprocessor = keras_nlp.models.AlbertPreprocessor.from_preset("albert_base_en_uncased")

In [172]:
preprocessor(string_arr_text)

{'token_ids': <tf.Tensor: shape=(2, 512), dtype=int32, numpy=
 array([[ 2, 13,  1, ...,  0,  0,  0],
        [ 2, 13,  1, ...,  0,  0,  0]], dtype=int32)>,
 'segment_ids': <tf.Tensor: shape=(2, 512), dtype=int32, numpy=
 array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=int32)>,
 'padding_mask': <tf.Tensor: shape=(2, 512), dtype=bool, numpy=
 array([[ True,  True,  True, ..., False, False, False],
        [ True,  True,  True, ..., False, False, False]])>}

In [173]:
model = keras_nlp.models.AlbertBackbone.from_preset("albert_base_en_uncased")

100%|██████████| 611/611 [00:00<00:00, 839kB/s]
100%|██████████| 44.6M/44.6M [00:01<00:00, 26.1MB/s]


In [174]:
model(preprocessor(string_arr_text))

{'sequence_output': <tf.Tensor: shape=(2, 512, 768), dtype=float32, numpy=
 array([[[ 0.29109532,  0.59039575,  0.57341796, ..., -1.7762976 ,
           0.8334062 ,  0.22888707],
         [ 0.23810953,  0.03257053,  0.14244957, ...,  0.13890208,
           0.97672796,  0.33284622],
         [-2.0244946 , -1.1321733 ,  1.7023356 , ...,  0.7105138 ,
           0.21753633, -1.2893486 ],
         ...,
         [-1.6347158 , -0.47780624,  0.7117915 , ...,  0.30713838,
           1.982284  , -1.0579503 ],
         [-1.5658598 , -0.40983802,  0.42121565, ..., -0.32397833,
           1.7305362 , -1.3411301 ],
         [ 0.10584101,  0.09978956, -0.0369747 , ..., -0.15564626,
           0.11278631,  0.18881346]],
 
        [[ 0.61990905,  1.5432444 ,  0.2692907 , ..., -1.582385  ,
           1.1010177 , -0.330584  ],
         [ 0.5509646 , -0.52529824, -0.445274  , ...,  0.2537047 ,
           1.1254579 , -0.5993581 ],
         [-0.95211315, -1.5976503 ,  1.5780841 , ...,  1.4106764 ,
         

In [175]:
preprocessor = keras_nlp.models.AlbertPreprocessor.from_preset("albert_large_en_uncased")

In [176]:
model = keras_nlp.models.AlbertBackbone.from_preset("albert_large_en_uncased")

100%|██████████| 610/610 [00:00<00:00, 699kB/s]
100%|██████████| 67.5M/67.5M [00:02<00:00, 31.8MB/s]


In [177]:
model(preprocessor(string_arr_text))

{'sequence_output': <tf.Tensor: shape=(2, 512, 1024), dtype=float32, numpy=
 array([[[ 0.2770636 , -0.1698493 ,  0.08749533, ..., -0.05548593,
           0.01278315,  0.6963581 ],
         [-0.72688234, -0.7326043 , -0.38781083, ...,  0.43813923,
          -1.4152989 , -0.06530092],
         [ 0.27033916,  0.19000015, -1.3199514 , ...,  0.1392531 ,
          -0.8895735 , -1.2217932 ],
         ...,
         [ 0.2773431 ,  0.66927105, -0.04740419, ..., -0.0374825 ,
          -0.77075374,  0.8259914 ],
         [ 0.518646  ,  0.66057897, -0.32028687, ...,  0.31278884,
          -0.5839745 ,  0.7095484 ],
         [ 0.41107494,  0.6453438 , -0.05412903, ...,  0.1492914 ,
          -0.58254355,  0.84967136]],
 
        [[-0.14092839, -0.33164838, -0.12895659, ..., -0.5563805 ,
          -0.5602438 ,  0.4876629 ],
         [-0.50146997,  0.06613347, -0.43767482, ...,  0.23815918,
          -1.0131388 , -0.3858407 ],
         [ 0.13780132, -0.06435348, -0.63802165, ..., -0.45307332,
        

In [179]:
preprocessor = keras_nlp.models.BertPreprocessor.from_preset("bert_tiny_en_uncased")

In [180]:
model = keras_nlp.models.BertBackbone.from_preset("bert_tiny_en_uncased")

100%|██████████| 507/507 [00:00<00:00, 754kB/s]
100%|██████████| 16.8M/16.8M [00:00<00:00, 19.2MB/s]


In [181]:
model(preprocessor(string_arr_text))

{'sequence_output': <tf.Tensor: shape=(2, 512, 128), dtype=float32, numpy=
 array([[[-0.00770359,  0.22362009, -3.8013916 , ..., -0.7977207 ,
          -1.6880293 ,  1.7669994 ],
         [-1.6496015 ,  0.15249002, -1.1784112 , ..., -1.7867173 ,
          -1.1260904 ,  0.7795008 ],
         [-1.5600612 , -0.21953619, -1.0176723 , ..., -1.7762308 ,
          -0.33892816,  2.633414  ],
         ...,
         [-0.30527773,  0.28472295, -0.75336015, ..., -1.456626  ,
          -0.9782943 ,  1.2421558 ],
         [-0.49452662,  0.41166344, -0.9690726 , ..., -1.2961192 ,
          -1.5198567 ,  0.53979856],
         [ 0.0641519 , -0.19211993, -2.706879  , ..., -0.68697417,
          -1.4666362 ,  1.7109971 ]],
 
        [[-0.354321  ,  0.9647313 , -3.847001  , ..., -0.80586714,
          -0.9092316 ,  1.3984995 ],
         [-1.835139  ,  0.6671057 , -1.078124  , ..., -1.630855  ,
          -0.78849745,  0.456828  ],
         [-1.4289438 ,  0.30635625, -0.9468864 , ..., -1.7343024 ,
         

In [186]:
preprocessor = keras_nlp.models.BertPreprocessor.from_preset("bert_base_en_uncased")

In [187]:
backbone = keras_nlp.models.BertBackbone.from_preset("bert_base_en_uncased")

100%|██████████| 510/510 [00:00<00:00, 665kB/s]
100%|██████████| 418M/418M [00:08<00:00, 51.9MB/s]


In [189]:
backbone(preprocessor(string_arr_text))

{'sequence_output': <tf.Tensor: shape=(2, 512, 768), dtype=float32, numpy=
 array([[[-0.20938647, -0.0447967 , -0.0179227 , ..., -0.30004027,
           0.48361152,  0.18294334],
         [ 0.32825446, -0.02166456, -0.39377376, ...,  0.11882182,
           0.6425974 ,  0.45160437],
         [ 0.528185  ,  0.39515415, -0.02727318, ..., -0.73575246,
           0.35064745, -0.5483459 ],
         ...,
         [-0.3357183 , -0.38612738, -0.06444541, ...,  0.29757988,
           0.30048501, -0.3327183 ],
         [-0.26773313, -0.31494525,  0.02369765, ...,  0.2863674 ,
           0.23007949, -0.21449938],
         [-0.4126262 , -0.30891353,  0.14669228, ...,  0.26272935,
           0.226851  , -0.04317985]],
 
        [[-0.07738914, -0.24507833,  0.1153888 , ..., -0.38911206,
           0.48910534,  0.07553282],
         [ 0.5525758 , -0.12614192, -0.5826222 , ..., -0.1812959 ,
           0.28061315,  0.2827501 ],
         [ 0.2549866 ,  0.25033718, -0.28970826, ..., -0.7006984 ,
         

In [190]:
preprocessor = keras_nlp.models.BertPreprocessor.from_preset("bert_base_multi")

In [191]:
backbone = keras_nlp.models.BertBackbone.from_preset("bert_base_multi")

100%|██████████| 511/511 [00:00<00:00, 679kB/s]
100%|██████████| 679M/679M [00:16<00:00, 42.2MB/s]


In [192]:
backbone(preprocessor(string_arr_text))

{'sequence_output': <tf.Tensor: shape=(2, 512, 768), dtype=float32, numpy=
 array([[[ 0.08711088,  0.11382888,  0.11536136, ...,  0.4214033 ,
          -0.09078561, -0.05034738],
         [-0.34812558,  0.23785737,  0.3641678 , ...,  0.1912393 ,
           0.42588252, -0.18637745],
         [-0.5351661 , -0.07008435,  0.11883144, ..., -0.3181511 ,
          -0.83528185, -0.2949006 ],
         ...,
         [-0.11932471,  0.24315329,  0.16223994, ...,  0.57475126,
           0.07621647, -0.16686553],
         [-0.14910577,  0.2541033 ,  0.2079171 , ...,  0.50970924,
           0.13872793, -0.17375654],
         [-0.14910062,  0.24503677,  0.28864548, ...,  0.44557023,
           0.2115266 , -0.19180845]],
 
        [[ 0.09399235,  0.02161617,  0.17021967, ...,  0.36230803,
           0.1955499 ,  0.01508363],
         [-0.21053134,  0.01779966,  0.381522  , ...,  0.05383883,
           0.5950641 ,  0.1696954 ],
         [-0.44740194, -0.29180452,  0.18786246, ..., -0.40811312,
         

In [193]:
preprocessor = keras_nlp.models.BloomPreprocessor.from_preset("bloom_560m_multi")

In [194]:
backbone = keras_nlp.models.BloomBackbone.from_preset("bloom_560m_multi")

100%|██████████| 491/491 [00:00<00:00, 639kB/s]
100%|██████████| 1.04G/1.04G [00:18<00:00, 59.3MB/s]


In [196]:
backbone(preprocessor(string_arr_text))

<tf.Tensor: shape=(2, 2048, 1024), dtype=float32, numpy=
array([[[ 2.1761465e+00,  3.2586002e+00,  1.0241686e+00, ...,
         -1.6263889e+02,  1.8448048e+00, -6.9300942e+00],
        [ 5.4194641e+00,  2.4093409e+00, -2.4139204e+00, ...,
          1.6557654e+02,  7.1409416e-01, -4.5761642e+00],
        [ 2.9769721e+00,  7.6612782e+00,  1.0352454e+00, ...,
          3.0262064e+02,  2.0435967e+00, -5.7509370e+00],
        ...,
        [ 2.9093158e+00,  6.9414515e+00,  9.3755923e-02, ...,
          6.0813019e+01,  5.6328015e+00, -8.2676344e+00],
        [ 2.9093158e+00,  6.9414515e+00,  9.3755923e-02, ...,
          6.0813019e+01,  5.6328015e+00, -8.2676344e+00],
        [ 2.9093158e+00,  6.9414515e+00,  9.3755923e-02, ...,
          6.0813019e+01,  5.6328015e+00, -8.2676344e+00]],

       [[ 2.1761465e+00,  3.2586002e+00,  1.0241686e+00, ...,
         -1.6263889e+02,  1.8448048e+00, -6.9300942e+00],
        [ 5.4194641e+00,  2.4093409e+00, -2.4139204e+00, ...,
          1.6557654e+02,  

In [197]:
preprocessor = keras_nlp.models.DebertaV3Preprocessor.from_preset("deberta_v3_extra_small_en")

In [198]:
backbone = keras_nlp.models.DebertaV3Backbone.from_preset("deberta_v3_extra_small_en")

100%|██████████| 539/539 [00:00<00:00, 701kB/s]
100%|██████████| 270M/270M [00:08<00:00, 35.2MB/s]


In [199]:
backbone(preprocessor(string_arr_text))

<tf.Tensor: shape=(2, 512, 384), dtype=float32, numpy=
array([[[-3.4626253 , -0.00978421, -0.12114353, ..., -0.12299246,
         -0.22639605,  0.7293565 ],
        [ 0.20320858,  0.8181175 ,  0.8702323 , ..., -0.54111135,
          0.03345384,  0.6470524 ],
        [ 0.5739167 ,  0.40295136, -0.31281596, ...,  1.011291  ,
          0.03529015,  0.59822714],
        ...,
        [ 1.3364415 ,  0.36981773,  0.05525   , ...,  0.42270583,
          0.1904701 ,  1.4155257 ],
        [ 1.3318508 ,  0.37212145,  0.05893942, ...,  0.43085775,
          0.19043136,  1.4249412 ],
        [ 1.3310525 ,  0.3815808 ,  0.05100167, ...,  0.4249448 ,
          0.19089667,  1.4413466 ]],

       [[-3.4284477 , -0.0043433 , -0.13300002, ..., -0.06028314,
         -0.2045255 ,  0.5065608 ],
        [-0.6611031 , -0.14433683,  1.0434818 , ...,  0.1567784 ,
         -0.03792468,  0.43380213],
        [-0.5769816 ,  0.36937016, -0.03237634, ...,  1.0018854 ,
          0.00702085,  0.2254726 ],
        ...,

In [200]:
preprocessor = keras_nlp.models.DistilBertPreprocessor.from_preset("distil_bert_base_multi")

In [201]:
backbone = keras_nlp.models.DistilBertBackbone.from_preset("distil_bert_base_multi")

100%|██████████| 516/516 [00:00<00:00, 588kB/s]
100%|██████████| 514M/514M [00:15<00:00, 35.3MB/s]


In [202]:
backbone(preprocessor(string_arr_text))

<tf.Tensor: shape=(2, 512, 768), dtype=float32, numpy=
array([[[-2.38554887e-02,  1.68186605e-01,  2.70602375e-01, ...,
          4.69620705e-01, -1.17200643e-01, -1.86264545e-01],
        [-2.37414554e-01,  2.69834399e-01,  1.22712567e-01, ...,
          1.34710252e-01,  3.13492455e-02, -4.43504870e-01],
        [-4.15596485e-01,  1.78933501e-01,  3.18474919e-01, ...,
         -2.53874481e-01, -6.53401077e-01, -4.22492176e-01],
        ...,
        [-1.26550436e-01,  1.83414266e-01,  4.12947059e-01, ...,
          3.36093783e-01,  7.91351572e-02, -2.73841619e-01],
        [-1.16294555e-01,  1.82058826e-01,  4.37204301e-01, ...,
          3.09447169e-01,  6.14488907e-02, -2.61272430e-01],
        [-6.95211440e-02,  2.16463149e-01,  4.62832749e-01, ...,
          2.26854935e-01,  1.05398208e-01, -2.76058584e-01]],

       [[-1.76659711e-02, -3.83704305e-02,  1.54110759e-01, ...,
          2.61661261e-01,  1.19499750e-01, -7.80541301e-02],
        [-2.80655354e-01,  3.75499129e-02,  7.76

In [203]:
preprocessor = keras_nlp.models.ElectraPreprocessor.from_preset("electra_small_generator_uncased_en")

In [204]:
backbone = keras_nlp.models.ElectraBackbone.from_preset("electra_small_generator_uncased_en")

100%|██████████| 545/545 [00:00<00:00, 818kB/s]
100%|██████████| 52.1M/52.1M [00:01<00:00, 35.6MB/s]


In [205]:
backbone(preprocessor(string_arr_text))

{'sequence_output': <tf.Tensor: shape=(2, 512, 256), dtype=float32, numpy=
 array([[[-0.39992166, -0.16135481, -0.78163683, ..., -0.57820135,
           0.22587287, -0.34859103],
         [-0.79113305, -1.3331983 ,  0.8153106 , ..., -0.515072  ,
           0.70025456, -1.0914644 ],
         [ 0.3458203 , -1.1328875 , -2.3620691 , ...,  0.16198406,
          -0.12645167,  0.40012652],
         ...,
         [-0.139808  , -1.918993  , -0.17399275, ...,  1.284367  ,
          -0.29759496,  1.2736673 ],
         [-0.13288808, -1.7916877 , -0.36186713, ...,  1.2850299 ,
          -0.33620223,  1.3557978 ],
         [-0.3995874 , -0.16118091, -0.78162163, ..., -0.57799625,
           0.22589925, -0.34855863]],
 
        [[-0.26406533, -0.20635216, -0.6462268 , ..., -0.5257906 ,
           0.2151193 , -0.4433258 ],
         [-0.9548582 , -1.542733  ,  0.8654411 , ..., -0.40517718,
           0.87316483, -0.99186826],
         [ 0.27427888, -1.7274584 , -1.7938777 , ...,  0.44326067,
         

In [206]:
preprocessor = keras_nlp.models.FNetPreprocessor.from_preset("f_net_base_en")

In [207]:
backbone = keras_nlp.models.FNetBackbone.from_preset("f_net_base_en")

100%|██████████| 488/488 [00:00<00:00, 585kB/s]
100%|██████████| 316M/316M [00:08<00:00, 37.1MB/s]


In [208]:
backbone(preprocessor(string_arr_text))

{'sequence_output': <tf.Tensor: shape=(2, 512, 768), dtype=float32, numpy=
 array([[[ 3.4832911 , -0.23926173, -0.29961383, ...,  0.73322713,
          -0.3210941 , -0.01858222],
         [ 0.02321588,  0.5242932 , -0.08457023, ...,  0.63765025,
          -0.21034247, -0.05132907],
         [-0.30167097, -0.73119915, -0.2022688 , ..., -0.12264019,
           0.335086  ,  0.55366236],
         ...,
         [-0.36634642, -0.01174078, -0.3611329 , ...,  1.2087095 ,
          -0.4886656 , -0.4481714 ],
         [-0.11147072,  0.23129179,  0.07656436, ...,  0.9504477 ,
          -0.5090325 , -0.6361706 ],
         [ 0.44594094, -0.34442985, -0.06136485, ...,  0.95593953,
          -0.26141393,  0.43901274]],
 
        [[ 3.512138  , -0.26546478, -0.40860572, ...,  0.5549449 ,
          -0.38026142, -0.09524231],
         [-0.14089565,  0.54892653, -0.15139505, ...,  0.6331389 ,
          -0.21829882,  0.00568292],
         [-0.54661447, -0.8897764 , -0.30514175, ..., -0.38637817,
         

In [209]:
preprocessor = keras_nlp.models.GPT2Preprocessor.from_preset("gpt2_base_en")

In [210]:
backbone = keras_nlp.models.GPT2Backbone.from_preset("gpt2_base_en")

100%|██████████| 484/484 [00:00<00:00, 483kB/s]
100%|██████████| 475M/475M [00:16<00:00, 29.9MB/s]


In [211]:
backbone(preprocessor(string_arr_text))

<tf.Tensor: shape=(2, 1024, 768), dtype=float32, numpy=
array([[[-0.06694581,  0.08811206, -0.30819836, ...,  0.03051005,
          0.05112388, -0.00185235],
        [-0.15791543,  0.20060161,  0.4151133 , ..., -0.25525507,
         -0.24341798,  0.2849792 ],
        [-0.29859865, -0.06806904, -0.0646246 , ...,  0.26489487,
         -0.2875113 , -0.31171936],
        ...,
        [ 0.1546482 , -0.36596096,  0.21783009, ...,  0.18365133,
         -0.21436831, -0.04764044],
        [ 0.15677984, -0.36682385,  0.21664037, ...,  0.18243225,
         -0.21319951, -0.04764147],
        [ 0.2753421 , -0.33916977,  0.79639333, ...,  0.13528223,
         -0.09512205, -0.04175306]],

       [[-0.06694581,  0.08811206, -0.30819836, ...,  0.03051005,
          0.05112388, -0.00185235],
        [-0.15791543,  0.20060161,  0.4151133 , ..., -0.25525507,
         -0.24341798,  0.2849792 ],
        [-0.29859865, -0.06806904, -0.0646246 , ...,  0.26489487,
         -0.2875113 , -0.31171936],
        ...

In [212]:
preprocessor = keras_nlp.models.OPTPreprocessor.from_preset("opt_125m_en")

In [213]:
backbone = keras_nlp.models.OPTBackbone.from_preset("opt_125m_en")

100%|██████████| 420/420 [00:00<00:00, 608kB/s]
100%|██████████| 478M/478M [00:17<00:00, 29.3MB/s]


In [214]:
backbone(preprocessor(string_arr_text))

<tf.Tensor: shape=(2, 2048, 768), dtype=float32, numpy=
array([[[-0.8376603 , -5.6759953 ,  0.75141513, ..., -2.2708879 ,
         -1.551302  ,  0.40465003],
        [-0.04905511, -4.423391  , -0.04958333, ...,  1.1149515 ,
         -1.0219436 ,  0.17528556],
        [-0.39034975, -2.6528978 , -1.6544158 , ...,  0.4254    ,
         -0.09362997, -0.29293486],
        ...,
        [-0.29252064, -4.4834857 ,  0.09362209, ...,  0.21643537,
          0.02122694,  0.8579341 ],
        [ 0.21039164, -3.8747075 ,  0.19428045, ..., -0.02988547,
         -0.04330236,  1.2050629 ],
        [ 0.23109967, -3.7447567 , -0.22688371, ..., -0.92261255,
          0.5337175 ,  1.0146625 ]],

       [[-0.8376603 , -5.6759953 ,  0.75141513, ..., -2.2708879 ,
         -1.551302  ,  0.40465003],
        [-0.04905511, -4.423391  , -0.04958333, ...,  1.1149515 ,
         -1.0219436 ,  0.17528556],
        [-0.39034975, -2.6528978 , -1.6544158 , ...,  0.4254    ,
         -0.09362997, -0.29293486],
        ...

In [215]:
preprocessor = keras_nlp.models.RobertaPreprocessor.from_preset("roberta_base_en")

In [216]:
backbone = keras_nlp.models.RobertaBackbone.from_preset("roberta_base_en")

100%|██████████| 498/498 [00:00<00:00, 758kB/s]
100%|██████████| 474M/474M [00:11<00:00, 44.2MB/s]


In [217]:
backbone(preprocessor(string_arr_text))

<tf.Tensor: shape=(2, 512, 768), dtype=float32, numpy=
array([[[-0.03680493,  0.08634835, -0.01406232, ..., -0.07361803,
         -0.04870203, -0.02318175],
        [-0.06701862,  0.0559752 , -0.01390374, ...,  0.2129887 ,
         -0.02422271,  0.03388537],
        [-0.17855687,  0.01525635, -0.012477  , ..., -0.22785595,
          0.14205618,  0.10377412],
        ...,
        [-0.06456192, -0.04095808,  0.04676941, ...,  0.1362018 ,
         -0.1365145 , -0.04729055],
        [-0.07318372, -0.01149316,  0.06375635, ...,  0.01423925,
         -0.11488927, -0.01623553],
        [-0.0286827 ,  0.08123396, -0.03634828, ..., -0.11862419,
         -0.05254801, -0.05666611]],

       [[-0.03106388,  0.09176657, -0.01543124, ..., -0.06844773,
         -0.05541074, -0.02093292],
        [-0.00603818,  0.01889469, -0.0136258 , ...,  0.3916943 ,
          0.08835359,  0.14886539],
        [-0.09955787, -0.02494508,  0.02027955, ..., -0.27872202,
          0.19699705,  0.13824835],
        ...,