In [1]:
!pip install keras keras_nlp tensorflow tensorflow-text

In [63]:
import keras, keras_nlp

In [120]:
string_arr_text = ["Bengaluru is the garden city of India", "Bengaluru is the tech hub"]

In [121]:
preprocessor = keras_nlp.models.AlbertPreprocessor.from_preset("albert_base_en_uncased")

In [122]:
preprocessor(string_arr_text)

{'token_ids': <tf.Tensor: shape=(2, 512), dtype=int32, numpy=
 array([[ 2, 13,  1, ...,  0,  0,  0],
        [ 2, 13,  1, ...,  0,  0,  0]], dtype=int32)>,
 'segment_ids': <tf.Tensor: shape=(2, 512), dtype=int32, numpy=
 array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=int32)>,
 'padding_mask': <tf.Tensor: shape=(2, 512), dtype=bool, numpy=
 array([[ True,  True,  True, ..., False, False, False],
        [ True,  True,  True, ..., False, False, False]])>}