In [1]:
!pip install keras keras_nlp tensorflow tensorflow-text

In [63]:
import keras, keras_nlp

In [64]:
string_text = "Bengaluru is the garden city of India"

In [65]:
tokenizer = keras_nlp.models.BartTokenizer.from_preset("bart_base_en")

In [66]:
tokenizer(string_text)

<tf.Tensor: shape=(10,), dtype=int32, numpy=
array([ 387, 3314,  337, 5515,   16,    5, 5671,  343,    9,  666],
      dtype=int32)>

In [67]:
tokenizer = keras_nlp.models.BartTokenizer.from_preset("bart_large_en")

In [68]:
tokenizer(string_text)

<tf.Tensor: shape=(10,), dtype=int32, numpy=
array([ 387, 3314,  337, 5515,   16,    5, 5671,  343,    9,  666],
      dtype=int32)>

In [69]:
tokenizer = keras_nlp.models.BertTokenizer.from_preset("bert_base_en")

In [70]:
tokenizer(string_text)

<tf.Tensor: shape=(8,), dtype=int32, numpy=
array([ 7756, 12328,  1110,  1103,  4605,  1331,  1104,  1726],
      dtype=int32)>

In [71]:
tokenizer = keras_nlp.models.BloomTokenizer.from_preset("bloom_560m_multi")

100%|██████████| 453/453 [00:00<00:00, 637kB/s]
100%|██████████| 11.9M/11.9M [00:00<00:00, 21.7MB/s]
100%|██████████| 3.98M/3.98M [00:00<00:00, 9.29MB/s]


In [72]:
tokenizer(string_text)

<tf.Tensor: shape=(8,), dtype=int32, numpy=
array([209443,   5046,    632,    368,  74872,  13014,    461,  11759],
      dtype=int32)>

In [73]:
tokenizer = keras_nlp.models.BloomTokenizer.from_preset("bloom_1.1b_multi")

100%|██████████| 453/453 [00:00<00:00, 610kB/s]
100%|██████████| 11.9M/11.9M [00:00<00:00, 18.8MB/s]
100%|██████████| 3.98M/3.98M [00:00<00:00, 9.31MB/s]


In [74]:
tokenizer(string_text)

<tf.Tensor: shape=(8,), dtype=int32, numpy=
array([209443,   5046,    632,    368,  74872,  13014,    461,  11759],
      dtype=int32)>

In [75]:
tokenizer = keras_nlp.models.BloomTokenizer.from_preset("bloomz_560m_multi")

100%|██████████| 453/453 [00:00<00:00, 689kB/s]
100%|██████████| 11.9M/11.9M [00:00<00:00, 21.4MB/s]
100%|██████████| 3.98M/3.98M [00:00<00:00, 9.29MB/s]


In [76]:
tokenizer(string_text)

<tf.Tensor: shape=(8,), dtype=int32, numpy=
array([209443,   5046,    632,    368,  74872,  13014,    461,  11759],
      dtype=int32)>

In [77]:
tokenizer = keras_nlp.models.DebertaV3Tokenizer.from_preset("deberta_v3_extra_small_en")

100%|██████████| 424/424 [00:00<00:00, 397kB/s]
100%|██████████| 2.35M/2.35M [00:00<00:00, 6.11MB/s]


In [78]:
tokenizer(string_text)

<tf.Tensor: shape=(7,), dtype=int32, numpy=array([27263,   269,   262,  2058,   707,   265,  1280], dtype=int32)>

In [79]:
tokenizer = keras_nlp.models.DebertaV3Tokenizer.from_preset("deberta_v3_base_multi")

100%|██████████| 424/424 [00:00<00:00, 645kB/s]
100%|██████████| 4.11M/4.11M [00:00<00:00, 9.57MB/s]


In [80]:
tokenizer(string_text)

<tf.Tensor: shape=(8,), dtype=int32, numpy=
array([   365, 140360,    340,    288,  23839,   9417,    305,   4784],
      dtype=int32)>

In [81]:
tokenizer = keras_nlp.models.DistilBertTokenizer.from_preset("distil_bert_base_en_uncased")

100%|██████████| 580/580 [00:00<00:00, 822kB/s]
100%|██████████| 226k/226k [00:00<00:00, 1.19MB/s]


In [82]:
tokenizer(string_text)

<tf.Tensor: shape=(8,), dtype=int32, numpy=
array([ 8191, 14129,  2003,  1996,  3871,  2103,  1997,  2634],
      dtype=int32)>

In [83]:
tokenizer = keras_nlp.models.DistilBertTokenizer.from_preset("distil_bert_base_multi")

100%|██████████| 581/581 [00:00<00:00, 749kB/s]
100%|██████████| 972k/972k [00:00<00:00, 3.01MB/s]


In [84]:
tokenizer("ಬೆಂಗಳೂರು ಸುಂದರವಾಗಿದೆ")

<tf.Tensor: shape=(10,), dtype=int32, numpy=
array([ 1284, 13833, 80382, 31903, 54686,  1294, 14284, 38114, 99977,
       27569], dtype=int32)>

In [85]:
tokenizer = keras_nlp.models.ElectraTokenizer.from_preset("electra_small_generator_uncased_en")

100%|██████████| 559/559 [00:00<00:00, 721kB/s]
100%|██████████| 226k/226k [00:00<00:00, 1.20MB/s]


In [86]:
tokenizer(string_text)

<tf.Tensor: shape=(8,), dtype=int32, numpy=
array([ 8191, 14129,  2003,  1996,  3871,  2103,  1997,  2634],
      dtype=int32)>

In [87]:
tokenizer = keras_nlp.models.ElectraTokenizer.from_preset("electra_base_generator_uncased_en")

100%|██████████| 559/559 [00:00<00:00, 869kB/s]
100%|██████████| 226k/226k [00:00<00:00, 1.20MB/s]


In [88]:
tokenizer(string_text)

<tf.Tensor: shape=(8,), dtype=int32, numpy=
array([ 8191, 14129,  2003,  1996,  3871,  2103,  1997,  2634],
      dtype=int32)>

In [89]:
tokenizer = keras_nlp.models.ElectraTokenizer.from_preset("electra_large_generator_uncased_en")

100%|██████████| 559/559 [00:00<00:00, 877kB/s]
100%|██████████| 226k/226k [00:00<00:00, 1.20MB/s]


In [90]:
tokenizer(string_text)

<tf.Tensor: shape=(8,), dtype=int32, numpy=
array([ 8191, 14129,  2003,  1996,  3871,  2103,  1997,  2634],
      dtype=int32)>

In [91]:
tokenizer = keras_nlp.models.FNetTokenizer.from_preset("f_net_base_en")

100%|██████████| 399/399 [00:00<00:00, 603kB/s]
100%|██████████| 692k/692k [00:00<00:00, 2.36MB/s]


In [92]:
tokenizer(string_text)

<tf.Tensor: shape=(9,), dtype=int32, numpy=
array([16135,    34, 11742,    65,    13,  3704,  1558,    39,  2869],
      dtype=int32)>

In [93]:
tokenizer = keras_nlp.models.FNetTokenizer.from_preset("f_net_large_en")

100%|██████████| 399/399 [00:00<00:00, 459kB/s]
100%|██████████| 692k/692k [00:00<00:00, 2.36MB/s]


In [94]:
tokenizer(string_text)

<tf.Tensor: shape=(9,), dtype=int32, numpy=
array([16135,    34, 11742,    65,    13,  3704,  1558,    39,  2869],
      dtype=int32)>

In [98]:
tokenizer = keras_nlp.models.GPT2Tokenizer.from_preset("gpt2_base_en")

100%|██████████| 448/448 [00:00<00:00, 592kB/s]
100%|██████████| 0.99M/0.99M [00:00<00:00, 3.09MB/s]
100%|██████████| 446k/446k [00:00<00:00, 1.76MB/s]


In [99]:
tokenizer(string_text)

<tf.Tensor: shape=(10,), dtype=int32, numpy=
array([   33,  1516,   282, 14717,   318,   262, 11376,  1748,   286,
        3794], dtype=int32)>

In [100]:
tokenizer = keras_nlp.models.GPT2Tokenizer.from_preset('gpt2_medium_en')

100%|██████████| 448/448 [00:00<00:00, 538kB/s]
100%|██████████| 0.99M/0.99M [00:00<00:00, 3.10MB/s]
100%|██████████| 446k/446k [00:00<00:00, 1.76MB/s]


In [101]:
tokenizer(string_text)

<tf.Tensor: shape=(10,), dtype=int32, numpy=
array([   33,  1516,   282, 14717,   318,   262, 11376,  1748,   286,
        3794], dtype=int32)>

In [102]:
tokenizer = keras_nlp.models.GPT2Tokenizer.from_preset("gpt2_large_en")

100%|██████████| 448/448 [00:00<00:00, 678kB/s]
100%|██████████| 0.99M/0.99M [00:00<00:00, 3.11MB/s]
100%|██████████| 446k/446k [00:00<00:00, 1.74MB/s]


In [103]:
tokenizer(string_text)

<tf.Tensor: shape=(10,), dtype=int32, numpy=
array([   33,  1516,   282, 14717,   318,   262, 11376,  1748,   286,
        3794], dtype=int32)>

In [104]:
tokenizer = keras_nlp.models.GPT2Tokenizer.from_preset("gpt2_extra_large_en")

100%|██████████| 448/448 [00:00<00:00, 689kB/s]
100%|██████████| 0.99M/0.99M [00:00<00:00, 2.92MB/s]
100%|██████████| 446k/446k [00:00<00:00, 1.76MB/s]


In [105]:
tokenizer(string_text)

<tf.Tensor: shape=(10,), dtype=int32, numpy=
array([   33,  1516,   282, 14717,   318,   262, 11376,  1748,   286,
        3794], dtype=int32)>

In [106]:
tokenizer = keras_nlp.models.GPT2Tokenizer.from_preset("gpt2_base_en_cnn_dailymail")

100%|██████████| 448/448 [00:00<00:00, 614kB/s]
100%|██████████| 0.99M/0.99M [00:00<00:00, 3.11MB/s]
100%|██████████| 446k/446k [00:00<00:00, 1.76MB/s]


In [107]:
tokenizer(string_text)

<tf.Tensor: shape=(10,), dtype=int32, numpy=
array([   33,  1516,   282, 14717,   318,   262, 11376,  1748,   286,
        3794], dtype=int32)>

In [110]:
tokenizer = keras_nlp.models.MistralTokenizer.from_preset("mistral_7b_en")

100%|██████████| 407/407 [00:00<00:00, 449kB/s]
100%|██████████| 482k/482k [00:00<00:00, 1.84MB/s]


In [111]:
tokenizer(string_text)

<tf.Tensor: shape=(9,), dtype=int32, numpy=
array([22047,   282, 19099,   349,   272,  8759,  2990,   302,  5558],
      dtype=int32)>

In [112]:
tokenizer = keras_nlp.models.MistralTokenizer.from_preset("mistral_0.2_instruct_7b_en")

100%|██████████| 407/407 [00:00<00:00, 528kB/s]
100%|██████████| 482k/482k [00:00<00:00, 1.85MB/s]


In [113]:
tokenizer(string_text)

<tf.Tensor: shape=(9,), dtype=int32, numpy=
array([22047,   282, 19099,   349,   272,  8759,  2990,   302,  5558],
      dtype=int32)>

In [114]:
tokenizer = keras_nlp.models.OPTTokenizer.from_preset("opt_125m_en")

100%|██████████| 443/443 [00:00<00:00, 611kB/s]
100%|██████████| 0.99M/0.99M [00:00<00:00, 3.10MB/s]
100%|██████████| 446k/446k [00:00<00:00, 1.74MB/s]


In [115]:
tokenizer(string_text)

<tf.Tensor: shape=(10,), dtype=int32, numpy=
array([ 387, 3314,  337, 5515,   16,    5, 5671,  343,    9,  666],
      dtype=int32)>

In [116]:
tokenizer = keras_nlp.models.RobertaTokenizer.from_preset("roberta_large_en")

100%|██████████| 463/463 [00:00<00:00, 672kB/s]
100%|██████████| 0.99M/0.99M [00:00<00:00, 3.10MB/s]
100%|██████████| 446k/446k [00:00<00:00, 1.74MB/s]


In [117]:
tokenizer(string_text)

<tf.Tensor: shape=(10,), dtype=int32, numpy=
array([ 387, 3314,  337, 5515,   16,    5, 5671,  343,    9,  666],
      dtype=int32)>