In [1]:
!pip install keras keras_nlp tensorflow tensorflow-text

In [63]:
import keras, keras_nlp

In [120]:
string_arr_text = ["Bengaluru is the garden city of India", "Bengaluru is the tech hub"]

In [171]:
preprocessor = keras_nlp.models.AlbertPreprocessor.from_preset("albert_base_en_uncased")

In [172]:
preprocessor(string_arr_text)

{'token_ids': <tf.Tensor: shape=(2, 512), dtype=int32, numpy=
 array([[ 2, 13,  1, ...,  0,  0,  0],
        [ 2, 13,  1, ...,  0,  0,  0]], dtype=int32)>,
 'segment_ids': <tf.Tensor: shape=(2, 512), dtype=int32, numpy=
 array([[0, 0, 0, ..., 0, 0, 0],
        [0, 0, 0, ..., 0, 0, 0]], dtype=int32)>,
 'padding_mask': <tf.Tensor: shape=(2, 512), dtype=bool, numpy=
 array([[ True,  True,  True, ..., False, False, False],
        [ True,  True,  True, ..., False, False, False]])>}

In [173]:
model = keras_nlp.models.AlbertBackbone.from_preset("albert_base_en_uncased")

100%|██████████| 611/611 [00:00<00:00, 839kB/s]
100%|██████████| 44.6M/44.6M [00:01<00:00, 26.1MB/s]


In [174]:
model(preprocessor(string_arr_text))

{'sequence_output': <tf.Tensor: shape=(2, 512, 768), dtype=float32, numpy=
 array([[[ 0.29109532,  0.59039575,  0.57341796, ..., -1.7762976 ,
           0.8334062 ,  0.22888707],
         [ 0.23810953,  0.03257053,  0.14244957, ...,  0.13890208,
           0.97672796,  0.33284622],
         [-2.0244946 , -1.1321733 ,  1.7023356 , ...,  0.7105138 ,
           0.21753633, -1.2893486 ],
         ...,
         [-1.6347158 , -0.47780624,  0.7117915 , ...,  0.30713838,
           1.982284  , -1.0579503 ],
         [-1.5658598 , -0.40983802,  0.42121565, ..., -0.32397833,
           1.7305362 , -1.3411301 ],
         [ 0.10584101,  0.09978956, -0.0369747 , ..., -0.15564626,
           0.11278631,  0.18881346]],
 
        [[ 0.61990905,  1.5432444 ,  0.2692907 , ..., -1.582385  ,
           1.1010177 , -0.330584  ],
         [ 0.5509646 , -0.52529824, -0.445274  , ...,  0.2537047 ,
           1.1254579 , -0.5993581 ],
         [-0.95211315, -1.5976503 ,  1.5780841 , ...,  1.4106764 ,
         

In [175]:
preprocessor = keras_nlp.models.AlbertPreprocessor.from_preset("albert_large_en_uncased")

In [176]:
model = keras_nlp.models.AlbertBackbone.from_preset("albert_large_en_uncased")

100%|██████████| 610/610 [00:00<00:00, 699kB/s]
100%|██████████| 67.5M/67.5M [00:02<00:00, 31.8MB/s]


In [177]:
model(preprocessor(string_arr_text))

{'sequence_output': <tf.Tensor: shape=(2, 512, 1024), dtype=float32, numpy=
 array([[[ 0.2770636 , -0.1698493 ,  0.08749533, ..., -0.05548593,
           0.01278315,  0.6963581 ],
         [-0.72688234, -0.7326043 , -0.38781083, ...,  0.43813923,
          -1.4152989 , -0.06530092],
         [ 0.27033916,  0.19000015, -1.3199514 , ...,  0.1392531 ,
          -0.8895735 , -1.2217932 ],
         ...,
         [ 0.2773431 ,  0.66927105, -0.04740419, ..., -0.0374825 ,
          -0.77075374,  0.8259914 ],
         [ 0.518646  ,  0.66057897, -0.32028687, ...,  0.31278884,
          -0.5839745 ,  0.7095484 ],
         [ 0.41107494,  0.6453438 , -0.05412903, ...,  0.1492914 ,
          -0.58254355,  0.84967136]],
 
        [[-0.14092839, -0.33164838, -0.12895659, ..., -0.5563805 ,
          -0.5602438 ,  0.4876629 ],
         [-0.50146997,  0.06613347, -0.43767482, ...,  0.23815918,
          -1.0131388 , -0.3858407 ],
         [ 0.13780132, -0.06435348, -0.63802165, ..., -0.45307332,
        

In [179]:
preprocessor = keras_nlp.models.BertPreprocessor.from_preset("bert_tiny_en_uncased")

In [180]:
model = keras_nlp.models.BertBackbone.from_preset("bert_tiny_en_uncased")

100%|██████████| 507/507 [00:00<00:00, 754kB/s]
100%|██████████| 16.8M/16.8M [00:00<00:00, 19.2MB/s]


In [181]:
model(preprocessor(string_arr_text))

{'sequence_output': <tf.Tensor: shape=(2, 512, 128), dtype=float32, numpy=
 array([[[-0.00770359,  0.22362009, -3.8013916 , ..., -0.7977207 ,
          -1.6880293 ,  1.7669994 ],
         [-1.6496015 ,  0.15249002, -1.1784112 , ..., -1.7867173 ,
          -1.1260904 ,  0.7795008 ],
         [-1.5600612 , -0.21953619, -1.0176723 , ..., -1.7762308 ,
          -0.33892816,  2.633414  ],
         ...,
         [-0.30527773,  0.28472295, -0.75336015, ..., -1.456626  ,
          -0.9782943 ,  1.2421558 ],
         [-0.49452662,  0.41166344, -0.9690726 , ..., -1.2961192 ,
          -1.5198567 ,  0.53979856],
         [ 0.0641519 , -0.19211993, -2.706879  , ..., -0.68697417,
          -1.4666362 ,  1.7109971 ]],
 
        [[-0.354321  ,  0.9647313 , -3.847001  , ..., -0.80586714,
          -0.9092316 ,  1.3984995 ],
         [-1.835139  ,  0.6671057 , -1.078124  , ..., -1.630855  ,
          -0.78849745,  0.456828  ],
         [-1.4289438 ,  0.30635625, -0.9468864 , ..., -1.7343024 ,
         

In [186]:
preprocessor = keras_nlp.models.BertPreprocessor.from_preset("bert_base_en_uncased")

In [187]:
backbone = keras_nlp.models.BertBackbone.from_preset("bert_base_en_uncased")

100%|██████████| 510/510 [00:00<00:00, 665kB/s]
100%|██████████| 418M/418M [00:08<00:00, 51.9MB/s]


In [189]:
backbone(preprocessor(string_arr_text))

{'sequence_output': <tf.Tensor: shape=(2, 512, 768), dtype=float32, numpy=
 array([[[-0.20938647, -0.0447967 , -0.0179227 , ..., -0.30004027,
           0.48361152,  0.18294334],
         [ 0.32825446, -0.02166456, -0.39377376, ...,  0.11882182,
           0.6425974 ,  0.45160437],
         [ 0.528185  ,  0.39515415, -0.02727318, ..., -0.73575246,
           0.35064745, -0.5483459 ],
         ...,
         [-0.3357183 , -0.38612738, -0.06444541, ...,  0.29757988,
           0.30048501, -0.3327183 ],
         [-0.26773313, -0.31494525,  0.02369765, ...,  0.2863674 ,
           0.23007949, -0.21449938],
         [-0.4126262 , -0.30891353,  0.14669228, ...,  0.26272935,
           0.226851  , -0.04317985]],
 
        [[-0.07738914, -0.24507833,  0.1153888 , ..., -0.38911206,
           0.48910534,  0.07553282],
         [ 0.5525758 , -0.12614192, -0.5826222 , ..., -0.1812959 ,
           0.28061315,  0.2827501 ],
         [ 0.2549866 ,  0.25033718, -0.28970826, ..., -0.7006984 ,
         

In [190]:
preprocessor = keras_nlp.models.BertPreprocessor.from_preset("bert_base_multi")

In [191]:
backbone = keras_nlp.models.BertBackbone.from_preset("bert_base_multi")

100%|██████████| 511/511 [00:00<00:00, 679kB/s]
100%|██████████| 679M/679M [00:16<00:00, 42.2MB/s]


In [192]:
backbone(preprocessor(string_arr_text))

{'sequence_output': <tf.Tensor: shape=(2, 512, 768), dtype=float32, numpy=
 array([[[ 0.08711088,  0.11382888,  0.11536136, ...,  0.4214033 ,
          -0.09078561, -0.05034738],
         [-0.34812558,  0.23785737,  0.3641678 , ...,  0.1912393 ,
           0.42588252, -0.18637745],
         [-0.5351661 , -0.07008435,  0.11883144, ..., -0.3181511 ,
          -0.83528185, -0.2949006 ],
         ...,
         [-0.11932471,  0.24315329,  0.16223994, ...,  0.57475126,
           0.07621647, -0.16686553],
         [-0.14910577,  0.2541033 ,  0.2079171 , ...,  0.50970924,
           0.13872793, -0.17375654],
         [-0.14910062,  0.24503677,  0.28864548, ...,  0.44557023,
           0.2115266 , -0.19180845]],
 
        [[ 0.09399235,  0.02161617,  0.17021967, ...,  0.36230803,
           0.1955499 ,  0.01508363],
         [-0.21053134,  0.01779966,  0.381522  , ...,  0.05383883,
           0.5950641 ,  0.1696954 ],
         [-0.44740194, -0.29180452,  0.18786246, ..., -0.40811312,
         

In [193]:
preprocessor = keras_nlp.models.BloomPreprocessor.from_preset("bloom_560m_multi")

In [194]:
backbone = keras_nlp.models.BloomBackbone.from_preset("bloom_560m_multi")

100%|██████████| 491/491 [00:00<00:00, 639kB/s]
100%|██████████| 1.04G/1.04G [00:18<00:00, 59.3MB/s]


In [196]:
backbone(preprocessor(string_arr_text))

<tf.Tensor: shape=(2, 2048, 1024), dtype=float32, numpy=
array([[[ 2.1761465e+00,  3.2586002e+00,  1.0241686e+00, ...,
         -1.6263889e+02,  1.8448048e+00, -6.9300942e+00],
        [ 5.4194641e+00,  2.4093409e+00, -2.4139204e+00, ...,
          1.6557654e+02,  7.1409416e-01, -4.5761642e+00],
        [ 2.9769721e+00,  7.6612782e+00,  1.0352454e+00, ...,
          3.0262064e+02,  2.0435967e+00, -5.7509370e+00],
        ...,
        [ 2.9093158e+00,  6.9414515e+00,  9.3755923e-02, ...,
          6.0813019e+01,  5.6328015e+00, -8.2676344e+00],
        [ 2.9093158e+00,  6.9414515e+00,  9.3755923e-02, ...,
          6.0813019e+01,  5.6328015e+00, -8.2676344e+00],
        [ 2.9093158e+00,  6.9414515e+00,  9.3755923e-02, ...,
          6.0813019e+01,  5.6328015e+00, -8.2676344e+00]],

       [[ 2.1761465e+00,  3.2586002e+00,  1.0241686e+00, ...,
         -1.6263889e+02,  1.8448048e+00, -6.9300942e+00],
        [ 5.4194641e+00,  2.4093409e+00, -2.4139204e+00, ...,
          1.6557654e+02,  

In [197]:
preprocessor = keras_nlp.models.DebertaV3Preprocessor.from_preset("deberta_v3_extra_small_en")

In [198]:
backbone = keras_nlp.models.DebertaV3Backbone.from_preset("deberta_v3_extra_small_en")

100%|██████████| 539/539 [00:00<00:00, 701kB/s]
100%|██████████| 270M/270M [00:08<00:00, 35.2MB/s]


In [199]:
backbone(preprocessor(string_arr_text))

<tf.Tensor: shape=(2, 512, 384), dtype=float32, numpy=
array([[[-3.4626253 , -0.00978421, -0.12114353, ..., -0.12299246,
         -0.22639605,  0.7293565 ],
        [ 0.20320858,  0.8181175 ,  0.8702323 , ..., -0.54111135,
          0.03345384,  0.6470524 ],
        [ 0.5739167 ,  0.40295136, -0.31281596, ...,  1.011291  ,
          0.03529015,  0.59822714],
        ...,
        [ 1.3364415 ,  0.36981773,  0.05525   , ...,  0.42270583,
          0.1904701 ,  1.4155257 ],
        [ 1.3318508 ,  0.37212145,  0.05893942, ...,  0.43085775,
          0.19043136,  1.4249412 ],
        [ 1.3310525 ,  0.3815808 ,  0.05100167, ...,  0.4249448 ,
          0.19089667,  1.4413466 ]],

       [[-3.4284477 , -0.0043433 , -0.13300002, ..., -0.06028314,
         -0.2045255 ,  0.5065608 ],
        [-0.6611031 , -0.14433683,  1.0434818 , ...,  0.1567784 ,
         -0.03792468,  0.43380213],
        [-0.5769816 ,  0.36937016, -0.03237634, ...,  1.0018854 ,
          0.00702085,  0.2254726 ],
        ...,

In [200]:
preprocessor = keras_nlp.models.DistilBertPreprocessor.from_preset("distil_bert_base_multi")

In [201]:
backbone = keras_nlp.models.DistilBertBackbone.from_preset("distil_bert_base_multi")

100%|██████████| 516/516 [00:00<00:00, 588kB/s]
100%|██████████| 514M/514M [00:15<00:00, 35.3MB/s]


In [202]:
backbone(preprocessor(string_arr_text))

<tf.Tensor: shape=(2, 512, 768), dtype=float32, numpy=
array([[[-2.38554887e-02,  1.68186605e-01,  2.70602375e-01, ...,
          4.69620705e-01, -1.17200643e-01, -1.86264545e-01],
        [-2.37414554e-01,  2.69834399e-01,  1.22712567e-01, ...,
          1.34710252e-01,  3.13492455e-02, -4.43504870e-01],
        [-4.15596485e-01,  1.78933501e-01,  3.18474919e-01, ...,
         -2.53874481e-01, -6.53401077e-01, -4.22492176e-01],
        ...,
        [-1.26550436e-01,  1.83414266e-01,  4.12947059e-01, ...,
          3.36093783e-01,  7.91351572e-02, -2.73841619e-01],
        [-1.16294555e-01,  1.82058826e-01,  4.37204301e-01, ...,
          3.09447169e-01,  6.14488907e-02, -2.61272430e-01],
        [-6.95211440e-02,  2.16463149e-01,  4.62832749e-01, ...,
          2.26854935e-01,  1.05398208e-01, -2.76058584e-01]],

       [[-1.76659711e-02, -3.83704305e-02,  1.54110759e-01, ...,
          2.61661261e-01,  1.19499750e-01, -7.80541301e-02],
        [-2.80655354e-01,  3.75499129e-02,  7.76